import { getD1 } from "../db";

type SeedTheme = {
  id: string;
  name: string;
  author: string;
  authorUrl: string;
  platform: string;
  mode: string;
  description: string;
  tags: string[];
  palette: string[];
  previewUrl: string;
  sourceUrl: string;
  downloadUrl: string;
  sourceName: string;
  sourceRepo: string;
  stars: number;
  license: string;
  verifiedVersion: string;
  featured: boolean;
  updatedAt: string;
};

const materialBase = "https://raw.githubusercontent.com/robinli/codex-material-themes/main/public/themes";
const skinBase = "https://raw.githubusercontent.com/Wangnov/awesome-codex-skins/main/skins";

export const seedThemes: SeedTheme[] = [
  {
    id: "blue-messenger-2007",
    name: "蓝色信使 2007 · Blue Messenger 2007",
    author: "SkinDex × You",
    authorUrl: "https://codex-skindex.vercel.app/",
    platform: "桌面端",
    mode: "浅色",
    description: "从用户参考图提炼的冰蓝渐变、三栏工作区与复古桌面软件质感；预览含 QQ 企鹅怀旧同人元素，当前可导入部分为原创配色。",
    tags: ["参考图生成", "QQ 怀旧同人", "复古蓝", "原生导入"],
    palette: ["#EAF6FF", "#18356A", "#1674D1"],
    previewUrl: "/themes/blue-messenger-2007.png",
    sourceUrl: "https://codex-skindex.vercel.app/#themes",
    downloadUrl: "https://codex-skindex.vercel.app/#themes",
    sourceName: "SkinDex Lab",
    sourceRepo: "skindex/lab",
    stars: 0,
    license: "非官方同人概念 · QQ 企鹅归腾讯所有",
    verifiedVersion: "概念预览 · codex-theme-v1",
    featured: true,
    updatedAt: "2026-07-18T13:18:00+08:00",
  },
  {
    id: "chalkboard-green",
    name: "Chalkboard Green",
    author: "Robin Li",
    authorUrl: "https://github.com/robinli",
    platform: "桌面端",
    mode: "深色",
    description: "沉稳低眩光的黑板绿配色，适合长时间阅读与专注工作。",
    tags: ["低眩光", "阅读", "原生导入"],
    palette: ["#18382B", "#E8E3D3", "#D4B95E"],
    previewUrl: `${materialBase}/Theme01.png`,
    sourceUrl: "https://github.com/robinli/codex-material-themes",
    downloadUrl: "https://codex-material-themes.bud4net.chatgpt.site/",
    sourceName: "Codex Material Themes",
    sourceRepo: "robinli/codex-material-themes",
    stars: 0,
    license: "仓库未声明",
    verifiedVersion: "codex-theme-v1",
    featured: true,
    updatedAt: "2026-07-17T13:07:21Z",
  },
  {
    id: "cafe-walnut",
    name: "Cafe Walnut",
    author: "Robin Li",
    authorUrl: "https://github.com/robinli",
    platform: "桌面端",
    mode: "深色",
    description: "温暖的胡桃木与奶油色，像傍晚咖啡馆里的阅读桌。",
    tags: ["暖色", "护眼", "原生导入"],
    palette: ["#3A241B", "#F1E2CF", "#D6A756"],
    previewUrl: `${materialBase}/Theme02.png`,
    sourceUrl: "https://github.com/robinli/codex-material-themes",
    downloadUrl: "https://codex-material-themes.bud4net.chatgpt.site/",
    sourceName: "Codex Material Themes",
    sourceRepo: "robinli/codex-material-themes",
    stars: 0,
    license: "仓库未声明",
    verifiedVersion: "codex-theme-v1",
    featured: false,
    updatedAt: "2026-07-17T13:07:21Z",
  },
  {
    id: "parchment-and-ink",
    name: "Parchment & Ink",
    author: "Robin Li",
    authorUrl: "https://github.com/robinli",
    platform: "桌面端",
    mode: "浅色",
    description: "柔和纸质底色，取材自墨水、活字印刷和旧书页。",
    tags: ["纸张", "浅色", "原生导入"],
    palette: ["#E4D8BE", "#302A25", "#8C5A3C"],
    previewUrl: `${materialBase}/Theme03.png`,
    sourceUrl: "https://github.com/robinli/codex-material-themes",
    downloadUrl: "https://codex-material-themes.bud4net.chatgpt.site/",
    sourceName: "Codex Material Themes",
    sourceRepo: "robinli/codex-material-themes",
    stars: 0,
    license: "仓库未声明",
    verifiedVersion: "codex-theme-v1",
    featured: false,
    updatedAt: "2026-07-17T13:07:21Z",
  },
  {
    id: "drafting-blue",
    name: "Drafting Blue",
    author: "Robin Li",
    authorUrl: "https://github.com/robinli",
    platform: "桌面端",
    mode: "深色",
    description: "深邃制图蓝搭配清晰字色，为结构化思考设计。",
    tags: ["蓝色", "专注", "原生导入"],
    palette: ["#163A52", "#DCE8EC", "#E0B85C"],
    previewUrl: `${materialBase}/Theme04.png`,
    sourceUrl: "https://github.com/robinli/codex-material-themes",
    downloadUrl: "https://codex-material-themes.bud4net.chatgpt.site/",
    sourceName: "Codex Material Themes",
    sourceRepo: "robinli/codex-material-themes",
    stars: 0,
    license: "仓库未声明",
    verifiedVersion: "codex-theme-v1",
    featured: false,
    updatedAt: "2026-07-17T13:07:21Z",
  },
  {
    id: "harbor-fog",
    name: "Harbor Fog",
    author: "Robin Li",
    authorUrl: "https://github.com/robinli",
    platform: "桌面端",
    mode: "浅色",
    description: "冷调蓝灰日光配清晰深色文字，适合平静有条理的阅读。",
    tags: ["冷调", "浅色", "原生导入"],
    palette: ["#D6E0E2", "#23343A", "#3F7183"],
    previewUrl: `${materialBase}/Theme08.png`,
    sourceUrl: "https://github.com/robinli/codex-material-themes",
    downloadUrl: "https://codex-material-themes.bud4net.chatgpt.site/",
    sourceName: "Codex Material Themes",
    sourceRepo: "robinli/codex-material-themes",
    stars: 0,
    license: "仓库未声明",
    verifiedVersion: "codex-theme-v1",
    featured: true,
    updatedAt: "2026-07-17T13:07:21Z",
  },
  {
    id: "amber-terminal",
    name: "Amber Terminal",
    author: "Robin Li",
    authorUrl: "https://github.com/robinli",
    platform: "桌面端",
    mode: "深色",
    description: "近黑底上的暖琥珀色，像为辨识度打造的精密终端。",
    tags: ["终端", "高对比", "原生导入"],
    palette: ["#17140F", "#F1DFC1", "#E6A84F"],
    previewUrl: `${materialBase}/Theme10.png`,
    sourceUrl: "https://github.com/robinli/codex-material-themes",
    downloadUrl: "https://codex-material-themes.bud4net.chatgpt.site/",
    sourceName: "Codex Material Themes",
    sourceRepo: "robinli/codex-material-themes",
    stars: 0,
    license: "仓库未声明",
    verifiedVersion: "codex-theme-v1",
    featured: false,
    updatedAt: "2026-07-17T13:07:21Z",
  },
  {
    id: "indigo-workwear",
    name: "Indigo Workwear",
    author: "Robin Li",
    authorUrl: "https://github.com/robinli",
    platform: "桌面端",
    mode: "深色",
    description: "深沉工装靛蓝搭配柔和文字与低彩度黄铜强调色。",
    tags: ["靛蓝", "低饱和", "原生导入"],
    palette: ["#1D2933", "#DDE1DE", "#AF9362"],
    previewUrl: `${materialBase}/Theme12.png`,
    sourceUrl: "https://github.com/robinli/codex-material-themes",
    downloadUrl: "https://codex-material-themes.bud4net.chatgpt.site/",
    sourceName: "Codex Material Themes",
    sourceRepo: "robinli/codex-material-themes",
    stars: 0,
    license: "仓库未声明",
    verifiedVersion: "codex-theme-v1",
    featured: false,
    updatedAt: "2026-07-17T13:07:21Z",
  },
  {
    id: "gilded-grandeur",
    name: "Gilded Grandeur",
    author: "Xuhuan Studio",
    authorUrl: "https://github.com/xuhuanstudio",
    platform: "全平台",
    mode: "深色",
    description: "黑曜石空间、克制金色细节与可独立选择的互动伙伴。",
    tags: ["场景皮肤", "互动伙伴", "Beta"],
    palette: ["#11100F", "#D8B56B", "#493B27"],
    previewUrl: "https://raw.githubusercontent.com/xuhuanstudio/codex-styler/main/docs/media/codex-theme-gilded-grandeur.webp",
    sourceUrl: "https://github.com/xuhuanstudio/codex-styler",
    downloadUrl: "https://github.com/xuhuanstudio/codex-styler/releases/tag/v0.2.0-beta.2",
    sourceName: "Codex Styler",
    sourceRepo: "xuhuanstudio/codex-styler",
    stars: 10,
    license: "Apache-2.0 / CC BY 4.0",
    verifiedVersion: "v0.2.0-beta.2",
    featured: true,
    updatedAt: "2026-07-18T02:23:29Z",
  },
  {
    id: "merry-big-top",
    name: "Merry Big Top",
    author: "Xuhuan Studio",
    authorUrl: "https://github.com/xuhuanstudio",
    platform: "全平台",
    mode: "双模式",
    description: "活泼马戏色彩、圆润舞台表面与轻快动态伙伴。",
    tags: ["场景皮肤", "动态", "Beta"],
    palette: ["#2C173D", "#FF7A59", "#B9F45B"],
    previewUrl: "https://raw.githubusercontent.com/xuhuanstudio/codex-styler/main/docs/media/codex-theme-merry-big-top.webp",
    sourceUrl: "https://github.com/xuhuanstudio/codex-styler",
    downloadUrl: "https://github.com/xuhuanstudio/codex-styler/releases/tag/v0.2.0-beta.2",
    sourceName: "Codex Styler",
    sourceRepo: "xuhuanstudio/codex-styler",
    stars: 10,
    license: "Apache-2.0 / CC BY 4.0",
    verifiedVersion: "v0.2.0-beta.2",
    featured: false,
    updatedAt: "2026-07-18T02:23:29Z",
  },
  {
    id: "fortune-pavilion",
    name: "财神聚宝阁 · Fortune Pavilion",
    author: "Wangnov",
    authorUrl: "https://github.com/Wangnov",
    platform: "桌面端",
    mode: "双模式",
    description: "基于 .codexskin v1 的素材化界面皮肤，提供真实应用截图。",
    tags: ["Certified", ".codexskin", "双模式"],
    palette: ["#241307", "#D8A936", "#C4472D"],
    previewUrl: `${skinBase}/caishen-jubao/previews/home.webp`,
    sourceUrl: "https://github.com/Wangnov/awesome-codex-skins/tree/main/skins/caishen-jubao",
    downloadUrl: "https://github.com/Wangnov/awesome-codex-skins/releases/latest",
    sourceName: "Awesome Codex Skins",
    sourceRepo: "Wangnov/awesome-codex-skins",
    stars: 13,
    license: "MIT（代码）/ 素材见原仓库",
    verifiedVersion: "Codex 26.707.91948",
    featured: true,
    updatedAt: "2026-07-18T02:54:17Z",
  },
  {
    id: "celestial-court",
    name: "凌霄金阙 · Celestial Court",
    author: "Wangnov",
    authorUrl: "https://github.com/Wangnov",
    platform: "桌面端",
    mode: "双模式",
    description: "通过自动化质量门并由维护者在真实 Codex 中验证的皮肤。",
    tags: ["Certified", ".codexskin", "双模式"],
    palette: ["#14233A", "#E2C376", "#B34A36"],
    previewUrl: `${skinBase}/celestial-court/previews/home.webp`,
    sourceUrl: "https://github.com/Wangnov/awesome-codex-skins/tree/main/skins/celestial-court",
    downloadUrl: "https://github.com/Wangnov/awesome-codex-skins/releases/latest",
    sourceName: "Awesome Codex Skins",
    sourceRepo: "Wangnov/awesome-codex-skins",
    stars: 13,
    license: "MIT（代码）/ 素材见原仓库",
    verifiedVersion: "Codex 26.707.91948",
    featured: false,
    updatedAt: "2026-07-18T02:54:17Z",
  },
  {
    id: "ming-imperial",
    name: "大明金阙 · Ming Imperial",
    author: "Wangnov",
    authorUrl: "https://github.com/Wangnov",
    platform: "桌面端",
    mode: "双模式",
    description: "包含真机预览、版本声明和可逆安装流程的认证皮肤。",
    tags: ["Certified", ".codexskin", "双模式"],
    palette: ["#25100D", "#C5A55A", "#892D28"],
    previewUrl: `${skinBase}/ming-imperial/previews/home.webp`,
    sourceUrl: "https://github.com/Wangnov/awesome-codex-skins/tree/main/skins/ming-imperial",
    downloadUrl: "https://github.com/Wangnov/awesome-codex-skins/releases/latest",
    sourceName: "Awesome Codex Skins",
    sourceRepo: "Wangnov/awesome-codex-skins",
    stars: 13,
    license: "MIT（代码）/ 素材见原仓库",
    verifiedVersion: "Codex 26.707.91948",
    featured: false,
    updatedAt: "2026-07-18T02:54:17Z",
  },
  {
    id: "underworld-tribunal",
    name: "幽都判府 · Underworld Tribunal",
    author: "Wangnov",
    authorUrl: "https://github.com/Wangnov",
    platform: "桌面端",
    mode: "双模式",
    description: "素材化 UI、实时 DOM 文字与完整还原能力组成的认证皮肤。",
    tags: ["Certified", ".codexskin", "双模式"],
    palette: ["#130E20", "#795EAA", "#D18C45"],
    previewUrl: `${skinBase}/underworld-yama/previews/home.webp`,
    sourceUrl: "https://github.com/Wangnov/awesome-codex-skins/tree/main/skins/underworld-yama",
    downloadUrl: "https://github.com/Wangnov/awesome-codex-skins/releases/latest",
    sourceName: "Awesome Codex Skins",
    sourceRepo: "Wangnov/awesome-codex-skins",
    stars: 13,
    license: "MIT（代码）/ 素材见原仓库",
    verifiedVersion: "Codex 26.707.91948",
    featured: false,
    updatedAt: "2026-07-18T02:54:17Z",
  },
];

const SEED_VERSION = "2026-07-18-v2";
let themeDataReady: Promise<void> | undefined;

async function setupThemeData() {
  const d1 = getD1();
  await d1.batch([
    d1.prepare(`CREATE TABLE IF NOT EXISTS themes (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL,
      author TEXT NOT NULL,
      author_url TEXT NOT NULL,
      platform TEXT NOT NULL,
      mode TEXT NOT NULL,
      description TEXT NOT NULL,
      tags TEXT NOT NULL,
      palette TEXT NOT NULL,
      preview_url TEXT NOT NULL,
      source_url TEXT NOT NULL,
      download_url TEXT NOT NULL,
      source_name TEXT NOT NULL,
      source_repo TEXT NOT NULL,
      stars INTEGER DEFAULT 0 NOT NULL,
      license TEXT DEFAULT '未声明' NOT NULL,
      verified_version TEXT DEFAULT '来源已核验' NOT NULL,
      featured INTEGER DEFAULT 0 NOT NULL,
      status TEXT DEFAULT 'approved' NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`),
    d1.prepare("CREATE INDEX IF NOT EXISTS themes_status_idx ON themes (status, featured, updated_at)"),
    d1.prepare(`CREATE TABLE IF NOT EXISTS submissions (
      id TEXT PRIMARY KEY NOT NULL,
      theme_name TEXT NOT NULL,
      author_name TEXT NOT NULL,
      repo_url TEXT NOT NULL UNIQUE,
      platform TEXT NOT NULL,
      notes TEXT DEFAULT '' NOT NULL,
      status TEXT DEFAULT 'pending' NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`),
    d1.prepare("CREATE INDEX IF NOT EXISTS submissions_status_idx ON submissions (status, created_at)"),
    d1.prepare(`CREATE TABLE IF NOT EXISTS theme_proposals (
      id TEXT PRIMARY KEY NOT NULL,
      theme_name TEXT NOT NULL,
      author_name TEXT NOT NULL,
      platform TEXT NOT NULL,
      notes TEXT DEFAULT '' NOT NULL,
      palette TEXT NOT NULL,
      preview_key TEXT NOT NULL,
      preview_mime TEXT NOT NULL,
      source_type TEXT DEFAULT 'skill-generated' NOT NULL,
      consent_at TEXT NOT NULL,
      status TEXT DEFAULT 'pending' NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`),
    d1.prepare("CREATE INDEX IF NOT EXISTS theme_proposals_status_idx ON theme_proposals (status, created_at)"),
    d1.prepare(`CREATE TABLE IF NOT EXISTS catalog_meta (
      key TEXT PRIMARY KEY NOT NULL,
      value TEXT NOT NULL,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`),
    d1.prepare(`CREATE TABLE IF NOT EXISTS theme_revisions (
      id TEXT PRIMARY KEY NOT NULL,
      theme_id TEXT NOT NULL,
      action TEXT NOT NULL,
      snapshot TEXT NOT NULL,
      editor_email TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`),
    d1.prepare("CREATE INDEX IF NOT EXISTS theme_revisions_theme_idx ON theme_revisions (theme_id, created_at)"),
  ]);

  const currentSeed = await d1.prepare("SELECT value FROM catalog_meta WHERE key = 'seed_version'").first<{ value: string }>();
  if (currentSeed?.value === SEED_VERSION) return;

  await d1.batch(seedThemes.map((theme) => d1.prepare(`INSERT INTO themes (
    id, name, author, author_url, platform, mode, description, tags, palette,
    preview_url, source_url, download_url, source_name, source_repo, stars,
    license, verified_version, featured, status, updated_at
  ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'approved', ?)
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    author = excluded.author,
    author_url = excluded.author_url,
    platform = excluded.platform,
    mode = excluded.mode,
    description = excluded.description,
    tags = excluded.tags,
    palette = excluded.palette,
    preview_url = excluded.preview_url,
    source_url = excluded.source_url,
    download_url = excluded.download_url,
    source_name = excluded.source_name,
    source_repo = excluded.source_repo,
    stars = excluded.stars,
    license = excluded.license,
    verified_version = excluded.verified_version,
    featured = excluded.featured,
    updated_at = excluded.updated_at
  WHERE NOT EXISTS (
    SELECT 1 FROM catalog_meta WHERE key = 'theme_override:' || excluded.id
  )`).bind(
      theme.id,
      theme.name,
      theme.author,
      theme.authorUrl,
      theme.platform,
      theme.mode,
      theme.description,
      JSON.stringify(theme.tags),
      JSON.stringify(theme.palette),
      theme.previewUrl,
      theme.sourceUrl,
      theme.downloadUrl,
      theme.sourceName,
      theme.sourceRepo,
      theme.stars,
      theme.license,
      theme.verifiedVersion,
      theme.featured ? 1 : 0,
      theme.updatedAt,
    )));

  await d1.prepare(`INSERT INTO catalog_meta (key, value, updated_at)
    VALUES ('seed_version', ?, CURRENT_TIMESTAMP)
    ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP`).bind(SEED_VERSION).run();
}

export function ensureThemeData() {
  if (!themeDataReady) {
    themeDataReady = setupThemeData().catch((error) => {
      themeDataReady = undefined;
      throw error;
    });
  }
  return themeDataReady;
}
